workflows:
  my-workflow:
    name: My workflow name
    labels:
      - QA
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    publishing:
      email:
        recipients:
          - arashmohmdi79@gmail.com
      scripts:
        - name: Install dependencies
          script: flutter pub get

        - name: Build APK
          script: flutter build apk

        # - name: Send APK to Email
        #   script: |
        #     # Replace `arashmohmdi79@gmail.com` with the email address you want to send the APK to
        #     curl -s --url "smtps://smtp.example.com:465" \
        #       --ssl-reqd \
        #       --mail-from "arashmohmdi79@gmail.com" \
        #       --mail-rcpt "arashmohmdi79@gmail.com" \
        #       --upload-file "./build/app/outputs/flutter-apk/app-release.apk" \
        #       --user "arashmohmdi79@gmail.com:Arashioi9" \
        #       --insecure

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk